version: '3'

services:
  bind:
    restart: always
    image: terryzwt/bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10001:10000/tcp"
    volumes:
      - ./bind:/data
    environment:
      - ROOT_PASSWORD=password
